package com.eclinic.db.model;

// default package
// Generated 2015-05-05 21:24:36 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name = "Task", catalog = "ira")
public class Task implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 213999008873524520L;
	private Integer id;
	private Users users;
	private byte[] description;
	private String name;
	private String shareTask;
	private Date dateOfCreate;

	public Task() {
	}

	public Task(Users users, byte[] description, String name, String shareTask,
			Date dateOfCreate) {
		this.users = users;
		this.description = description;
		this.name = name;
		this.shareTask = shareTask;
		this.dateOfCreate = dateOfCreate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "description", nullable = false)
	public byte[] getDescription() {
		return this.description;
	}

	public void setDescription(byte[] description) {
		this.description = description;
	}

	@Column(name = "name", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "share_task", nullable = false, length = 1)
	public String getShareTask() {
		return this.shareTask;
	}

	public void setShareTask(String shareTask) {
		this.shareTask = shareTask;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_of_create", nullable = false, length = 10)
	public Date getDateOfCreate() {
		return this.dateOfCreate;
	}

	public void setDateOfCreate(Date dateOfCreate) {
		this.dateOfCreate = dateOfCreate;
	}

}
